version: "2017-09-20"
pipeline:
  - id: build
    type: script
    overlay: ci/python
    commands:
    - desc: "Install dependencies"
      cmd: pip3 install -U  setuptools -r requirements.txt
    - desc: Run tests
      cmd: python3 setup.py test
    - desc: Build and push a Docker Image  # The image should be buildable even if not uploaded
      cmd: |
        IMAGE=pierone.stups.zalan.do/automata/lizzy:cdp${CDP_TARGET_BRANCH_COUNTER}
        docker build -t "$IMAGE" .
        if [ -z "$CDP_PULL_REQUEST_NUMBER" ]; then
          docker push "$IMAGE"
        else
          echo "Image not pushed because the build is not a push to master"
        fi
