version: "2017-09-20"
pipeline:
  - id: build
    type: script
    overlay: ci/python
    commands:
    - desc: "Setup OS packages"
      cmd: apt-get install -y python-dev
    - desc: "Setup Pipenv"
      cmd: pipenv install --dev --deploy
    - desc: Run tests
      cmd: pipenv run make ci-checks
    - desc: Build and push a Docker Image  # The image should be buildable even if not uploaded
      cmd: |
        IMAGE=pierone.stups.zalan.do/automata/lizzy:cdp${CDP_TARGET_BRANCH_COUNTER}
        docker build -t "$IMAGE" .
        if [ -z "$CDP_PULL_REQUEST_NUMBER" ]; then
          docker push "$IMAGE"
        else
          echo "Image not pushed because the build is not a push to master"
        fi
