from typing import Dict, Any, List, Optional  # NOQA  pylint: disable=unused-import

from lizzy.exceptions import ObjectNotFound
from ..apps.senza import Senza
from ..util import timestamp_to_uct
from ..configuration import config

REMOVED_STACK = object()


class Stack():
    prefix = 'lizzy_stack'
    key = 'stack_id'
    search_properties = ['stack_id']

    def __init__(self, *,
                 stack_name: str,
                 creation_time: int,
                 description: str,
                 version: str,
                 status: str):
        """
        Stack Model stored in Redis

        :param stack_id: Id of the stack used both in Lizzy and Cloud Formation (Generated by Lizzy)
        :param creation_time: Date and time of stack creation
        :param keep_stacks: How many old stacks to keep
        :param traffic: How much traffic to route to new stack
        :param image_version: Docker image version to deploy
        :param ami_image: Which AMI image to use
        :param stack_name: Name of the application
        :param stack_version: Stack Version (generated by Lizzy)
        :param parameters: Parameters to pass to Senza
        :param status: Stack Status
        :param kwargs: Other parameters that are not recognized
        """
        self.stack_name = stack_name
        self.creation_time = timestamp_to_uct(creation_time)
        self.description = description
        self.version = version
        self.status = status
        self.__cf_stack = None

    @classmethod
    def get(cls, stack_name: str, stack_version: str) -> 'Stack':
        stacks = cls.list(stack_name, stack_version)
        if not stacks:
            raise ObjectNotFound('{}-{}'.format(stack_name, stack_version))
        else:
            return stacks[0]

    @classmethod
    def list(cls, *stack_ref: List[str]) -> List['Stack']:
        """
        Returns a List of stack dicts compliant with the API spec.

        .. seealso:: lizzy/swagger/lizzy.yaml#/definitions/stack
        """

        senza = Senza(config.region)
        stacks = [Stack(**stack)
                  for stack in senza.list(*stack_ref)]
        return stacks

    def generate_id(self) -> str:
        """
        The id will be the same as the stack name on aws
        """
        return '{name}-{version}'.format(name=self.stack_name,
                                         version=self.stack_version)
